### ISSUE TITLE
Graphql query errors

### ISSUE THREAD

**Issue by magick93** [roapi/roapi#138]
Hello

I'm trying to get the graphql query functionality working and am struggling to get even a basic query to work. 

I've tried the following (using both the http client in vscode and the Thunder client:

```
POST http://localhost:8080/api/graphql
Accept: application/json
X-REQUEST-TYPE: GraphQL

query test {
  spacex_launches {
      name
  }
}
```

But this returns the following error:
```
HTTP/1.1 400 Bad Request
content-length: 150
date: Sun, 06 Feb 2022 23:52:29 GMT

{"code":400,"error":"invalid graphql query","message":"query parse error: Parse error at 1:2\nUnexpected `\"query\"[StringValue]`\nExpected `Name`\n"}
```

I'm using the following config:
```
tables:
  - name: "spacex_launches"
    uri: "https://api.spacexdata.com/v4/launches"
    option:
      format: "json"
```
