### ISSUE TITLE
database support

### ISSUE THREAD

**Issue by geoHeil** [roapi/roapi#178]
For 0.7.1 and a configuration of:

```
tables:
  - name: "table_foo"
    uri: "mysql://username:password@localhost:3306/database"
    #uri: "table_foo=mysql://username:password@localhost:3306/database"

```

In any case I get:

```
 Invalid table URI: cannot detect table extension from uri: mysql://username:password@server:port/databas

```

back as a result - how can I tell roapi to actually use either postgres or MySQL? In both cases the table is not identified
