### ISSUE TITLE
GCS S3-type access

### ISSUE THREAD

**Issue by dantodor** [roapi/roapi#186]
As per Google's documentation:
https://cloud.google.com/storage/docs/aws-simple-migration 
GCS bucket can be made to appear from the client's perspective as S3 bucket. 
I did everything Google suggested in that page, and configured the following env variables before starting roapi:
AWS_ACCESS_KEY_ID=...
AWS_SECRET_ACCESS_KEY=...
AWS_ENDPOINT_URL="storage.googleapis.com" ( tried with "https://" too)

Still, what I get is 
```
Error: DataFusion error: IO error: No such file or directory (os error 2)

Caused by:
    IO error: No such file or directory (os error 2)
```

File is definitely there. Is there something else that I can try ?
PS I see GCS integration is on the roadmap, just trying to find an easy way in between.

**Comment by houqp** [comment]
Thanks Dan for the report, could you give it another try after https://github.com/roapi/roapi/pull/187 gets merged? For the endpoint, you should provide a full URI with `https` scheme.

It would be helpful if you can run it with `RUST_LOG=debug` to help gather more debug info.

**Comment by dantodor** [comment]
I'll do that. I just realized I forgot to set the region too.I presume it's AWS_REGION ?

**Comment by houqp** [comment]
that's correct

**Comment by dantodor** [comment]
@houqp  Okay, so I found a little bit of time to play around with it. Still no luck. 

Config file looks like this:

```
addr:
  # binding address for TCP port that speaks HTTP protocol
  http: 0.0.0.0:8084
  # binding address for TCP port that speaks Postgres wire protocol
  postgres: 0.0.0.0:5432
tables:
  - name: "nyc"
    uri: "s3://*redacted*/nycdata/data.parquet"
    option:
      format: "parquet"
      use_memory_table: false

```

I'm starting `roapi` like this:

```
export AWS_ACCESS_KEY_ID=...
export AWS_SECRET_ACCESS_KEY=...
export AWS_ENDPOINT_URL="https://storage.googleapis.com"
export AWS_REGION=asia-southeast2
RUST_LOG=debug roapi -c ./roapi.yml
```

Result:

```
2022-10-01T08:20:21Z DEBUG datafusion::execution::memory_manager] Creating memory manager with initial size 11744051.2 TB
[2022-10-01T08:20:21Z INFO  roapi::context] loading `uri(s3://*redacted/nycdata/data.parquet)` as table `nyc`
[2022-10-01T08:20:21Z DEBUG datafusion::execution::memory_manager] Creating memory manager with initial size 11744051.2 TB
Error: DataFusion error: Internal error: No suitable object store found for s3://*redacted/nycdata/data.parquet. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker

Caused by:
    Internal error: No suitable object store found for s3://*redacted*/nycdata/data.parquet. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

Any ideas what else I could try?

Thank you!

**Comment by dantodor** [comment]
To add a little bit more context, this works:
```
import boto3

google_access_key_secret =  "..."
google_access_key_id = "..."


client = boto3.resource(
        "s3",
        region_name="auto",
        endpoint_url="https://storage.googleapis.com",
        aws_access_key_id=google_access_key_id,
        aws_secret_access_key=google_access_key_secret,
    )

obj = client.Object('***','nycdata/data.parquet')
data=obj.get()['Body'].read()
print(data)
```

I know, it's Python, but wanted to make sure it works from a programming language.

**Comment by jychen7** [comment]
> Error: DataFusion error: Internal error: No suitable object store found for s3://*redacted/nycdata/data.parquet. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker


apparently, I can reproduce and I think the root cause is NOT about GCS, it fails for S3 as well when `use_memory_table: false`
```
uri: "s3://*redacted*/nycdata/data.parquet"
    option:
      format: "parquet"
      use_memory_table: false
```

this is also reported in https://github.com/roapi/roapi/issues/227, related to Object Store Registry
