### ISSUE TITLE
Changing the default response serialization in the config.yaml

### ISSUE THREAD

**Issue by RalfNorthman** [roapi/roapi#212]
For certain use-cases [setting an http header](https://roapi.github.io/docs/api/response.html) is awkward or impossible, e.g. when specifying the data source in a vega or vega-lite visualization ([you can set what format to parse as, but not the header](https://vega.github.io/vega-lite/docs/data.html#url)). Therefore it would be nice if it were possible to change the default response serialization in the config.yaml.

Changing the default format from `application/json` to `application/vnd.apache.arrow.stream` could look something like this:
```yaml
addr:
   http: 0.0.0.0:8084
response_format: "vnd.apache.arrow.stream"
tables:
  - name: "blogs"
    uri: "test_data/blogs.parquet"
```
