### ISSUE TITLE
Unable to connect to MariaDb/MySQL 

### ISSUE THREAD

**Issue by accforgithubtest** [roapi/roapi#319]
Hello there, and thank your for this interesting project!

I am looking to try out using roapi, with mariadb and getting the error below in logs.

Installation / setup is using docker compose (not swarm), on a ubuntu host machine on which mariadb is also running.
I have other applications running in my self hosted set up, and the database is working fine with the other applications with the same connection string.

Below are my docker-compose.yaml, roapi.yml and the logs I see.
Any help is greatly appreciated. TIA.

```yaml
services:
  roapi:
    image: ghcr.io/roapi/roapi:latest
    container_name: roapi
    command: --config /config/roapi.yml
    environment:
      - RUST_BACKTRACE=1
    ports:
      - 8080
      - 5432
      - 32010
    volumes:
      - ./config:/config
```

```yaml
addr:
  # binding address for TCP port that speaks HTTP protocol
  http: 0.0.0.0:8000
  # binding address for TCP port that speaks Postgres wire protocol
  postgres: 0.0.0.0:5432
  
# List All Data Sources
tables:

  - name: "testtbl"
    uri: "mysql://test:pwd1234@mariadb:3306/testtbl"
```

```
[2024-03-13T06:45:52Z INFO  roapi::context] loading `uri(mysql://test:pwd1234@mariadb:3306/testtbl)` as table `testtbl`
thread 'main' panicked at /roapi_src/roapi/src/startup.rs:63:14:
Failed to create Roapi context: Whatever { source: Some(TableError { source: Extension { msg: "unsupported extension in uri: mysql://test:pwd1234@mariadb:3306/testtbl" } }), message: "Failed to load table", backtrace: Backtrace(()) }
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/20999de3a2f866a6006169c9bc188017aba79fcc/library/std/src/panicking.rs:619:5
   1: core::panicking::panic_fmt
             at ./rustc/20999de3a2f866a6006169c9bc188017aba79fcc/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at ./rustc/20999de3a2f866a6006169c9bc188017aba79fcc/library/core/src/result.rs:1652:5
   3: roapi::startup::Application::build::{{closure}}
   4: roapi::main::{{closure}}
   5: roapi::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
      
```
