### ISSUE TITLE
Unsupported datatype: Date32

### ISSUE THREAD

**Issue by linrium** [roapi/roapi#33]
I had an error when querying the data that had the `Date32` type. I checked DataFusion library but it works on Date32.

thread 'actix-rt|system:0|arbiter:5' panicked at 'Unsupported datatype: Date32', /Users/runner/.cargo/git/checkouts/arrow-7d34e669e95701bb/f7cf157/rust/arrow/src/json/writer.rs:326:13

Reproduce:
Config:
```yml
addr: 0.0.0.0:8080
tables:
- name: han_shop
  option:
    format: csv
  uri: ../examples.csv
```
SQL query:
```sql
SELECT name FROM example
```

CSV data:
```csv
period,name,
2021-03-01,Linh,
2021-03-01,Han,
```

Schema:
```json
{
    "name": "period",
    "data_type": "Date32",
    "nullable": false,
    "dict_id": 0,
    "dict_is_ordered": false
}
```

Command:
```bash
roapi-http -c ./config-1615885382668.yml
```
