### ISSUE TITLE
[Help] For XLSX file, start data from a certain row number ?

### ISSUE THREAD

**Issue by accforgithubtest** [roapi/roapi#357]
When using a xlsx file ([like this example](https://www.abs.gov.au/statistics/people/population/overseas-migration/2023-24/34070DO001_202324.xlsx)), is it possible to start reading the data only from a certain row number ?
Couldnt find any examples for this in the docs, but if it is somehow possible, it would be awesome.

In that sample file, I would only want to read the data from row `14` for sheet `Table 1.1`.
Is it possible to do something like

```
tables:
    - name: "excel_table"
      uri: "path/to/file.xlsx"
      option:
        format: "xlsx"
        sheet_name: "Sheet1"
        startFromRow: 14
```

**Comment by houqp** [comment]
you can set the start and end range through these options: https://github.com/roapi/roapi/blob/main/columnq/src/table/mod.rs#L270

**Comment by accforgithubtest** [comment]
thank you for the quick repl @houqp ! that is awesome.

For the same [example file](https://www.abs.gov.au/statistics/people/population/overseas-migration/2023-24/34070DO001_202324.xlsx), I tried below and getting the error `Failed to create Roapi context: Whatever { source: Some(TableError { source: LoadExcel { source: Load { msg: "The 1th column name is empty" } } }), message: "Failed to load table", backtrace: Backtrace(()) }`

Any suggestions on what I could try next to get the data from the xlsx file ?

Thanks for your help again, I will try to write this up as a working example for the docs if you are interested .

```yaml
  - name: "test_xlsx"
    uri: "/data/test.xlsx"
    option:
        format: "xlsx"
        sheet_name: "Table 1.1"
        rows_range_start: 14
        rows_range_end: 264
        columns_range_start: 1
```

If I didnt specify the columns_range_start, I see error `The 0th column name is empty`
