### ISSUE TITLE
Sending Headers to uri ?

### ISSUE THREAD

**Issue by accforgithubtest** [roapi/roapi#358]
`https://data.api.abs.gov.au/rest/dataflow` api responds with either json or xml response.
Unfortunately, they default to xml response, and the only option to specify json response is via headers, no query params.

To get json response from api, I need to pass headers for `accept` as `application/vnd.sdmx.structure+json; charset=utf-8`.
Is there any way to pass headers to the request uri ?

```
- name: "test_request_headers"
    uri: "https://data.api.abs.gov.au/rest/dataflow"
    option:
        format: "json"
```
