### ISSUE TITLE
Selecting files with Glob pattern / regexp when registering a table

### ISSUE THREAD

**Issue by tiphaineruy** [roapi/roapi#90]
Note sure if it could be interesting  but:

When registering a table:

```
addr: 0.0.0.0:8084
tables:
  - name: "example"
    uri: "/data/"
    option:
      format: "parquet"
      use_memory_table: false
```
  add in options:
glob
 > pattern: "*file_type*v1*.parquet"

or regexp
> pattern: "\w*file_type\w*v1\w*\.parquet"

It would allow selecting in uri's with different extension / schema version
